spring:
  application:
    name: microservice-a
  cloud.config.uri: http://localhost:8888

#server:
#  port: 8081

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#  instance:
#    preferIpAddress: true
